# Generated by Django 2.2.2 on 2019-08-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tddsquestions',
            name='question_haha',
        ),
    ]
